### ISSUE TITLE
Black screen after trying to start Sway WM

### ISSUE THREAD

**Issue by silvolde428** [archcraft-os/archcraft-sway#3]
Maybe a mistake on my part, but I'm getting a black screen when I try Sway on startup. I know for sure it's not a Wayland issue, as my nvidia GPU worked fine on Fedora 36. So is there maybe some kind of program or dependency I'm missing here on Archcraft?

**Comment by adi1090x** [comment]
@silvolde428 sorry for delayed response.

No, If you installed the package for Archcraft, all the dependencies should be installed also. But crosscheck with README of this repo and make sure all programs are installed.

My best guess is that Nvidia is causing that issue.  [check here](https://github.com/archcraft-os/archcraft-sway#fyi)
