### ISSUE TITLE
Crypto payment address

### ISSUE THREAD

**Issue by aurabindo** [archcraft-os/archcraft-sway#4]
I would like to pay but I dont like the idea of phone number being mandatory to make the payment. Would you accept some form of crypto payments? Bitcoin/Ethereum has huge gas price so I wouldnt use it anyway. Stellar (XLM) is a great choice IMO. Also, my paypal account's currency doesnt support transferring money to you.

Would you consider accepting any form of crypto payment?

**Comment by adi1090x** [comment]
There's no such case `as mandatory phone number`. My Ko-fi uses paypal for payment and with paypal you can make the payment as a guest as well.

Sorry, But i don't accept cryptos.
