### ISSUE TITLE
Keyboard changed to us

### ISSUE THREAD

**Issue by keybasegit** [archcraft-os/archcraft-sway#7]
Following the instruction I have installed archcraft, download, unpack and install sway.tar.gz. 

Keyboard layout changed in sway session to layout us. I have changed it in

 sway-input to xkb_layout gb,

 check vconsole.config where it's KEYMAP=uk

Log out. Reboot. Problem persist. I am unable to change keyboard leayout.

**Comment by adi1090x** [comment]
For input related setting, edit `~/.config/sway/sway-input` file.
