### ISSUE TITLE
sway under nvidia --unsupported-gpu

### ISSUE THREAD

**Issue by crashbit666** [archcraft-os/archcraft-sway#8]
After install archcraft prime with only sway desktop, I need to edit run-sway script to access to desktop.

sway need to add sway --unsupported-gpu if you are using nvidia.

/usr/local/bin/run-sway:
change last line
exec sway to exec sway --unsupported-gpu

**Comment by adi1090x** [comment]
Alright, I'll Update the wrapper script. Thanks.
