### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by apinter** [archcraft-os/archcraft-sway#9]
Hi,

I'm planning a sway build using your config, but this will likely result in me including your work in my publicly available flakes repo on Github. Sadly, I can't find any license in the purchased config, and I also don't want to cause you any issues. Please advise.

FTR: not planning to profit off or take credit for your work, this is simply how I manage my workstations.

**Comment by adi1090x** [comment]
![Screenshot_2024-10-19-20-26-54_1920x1080](https://github.com/user-attachments/assets/fb4c63a8-e141-49c7-a5c3-7bd283c9ba42)

There's  a license in the package. You can use the configs for your private repos, But you're not allowed to put the files in a public repo.
